terraform {
  required_providers { vpsk3s = { source = "igorovh/k3s-vps-wg", version = "0.1.0" } }
}

variable "pipeline_wireguard_public_key" {
  type        = string
  description = "WireGuard public key generated by the CI/CD pipeline. Keep the private key in CI secrets."
}

provider "vpsk3s" {
  ssh_user             = "root"
  ssh_private_key_path = "~/.ssh/id_ed25519"
}

resource "vpsk3s_cluster" "example" {
  name = "team-admin-peers"

  admin_peers = {
    igor = {
      public_key = "IGOR_WIREGUARD_PUBLIC_KEY"
      wg_ip      = "10.10.0.250"
    }

    ania = {
      public_key = "ANIA_WIREGUARD_PUBLIC_KEY"
      wg_ip      = "10.10.0.251"
    }

    pipeline = {
      public_key = var.pipeline_wireguard_public_key
      wg_ip      = "10.10.0.254"
    }

    generated_breakglass = {
      wg_ip = "10.10.0.253"
    }
  }

  nodes = [
    { public_ip = "203.0.113.61", role = "server" },
  ]
}

output "generated_admin_wireguard_configs" {
  value     = vpsk3s_cluster.example.admin_wireguard_configs
  sensitive = true
}
